/* Textes de la section « Avis clients » et de la page de dépôt, par langue.
   Module sans dépendance Astro : utilisable par les îlots React et les pages. */
import type { Lang } from '../../i18n';

export const projetsLibelles = {
  fr: {
    'Résidence Principale': 'Résidence Principale',
    'Appartement Locatif': 'Appartement Locatif',
    'Immeuble Locatif': 'Immeuble Locatif',
    'Immobilier Pro': 'Immobilier Pro',
    'Mobilier Pro': 'Mobilier Pro',
    'LBO/OBO': 'LBO / OBO',
    'Restructuration de dette': 'Restructuration de dette',
  },
  en: {
    'Résidence Principale': 'Primary residence',
    'Appartement Locatif': 'Buy-to-let flat',
    'Immeuble Locatif': 'Buy-to-let building',
    'Immobilier Pro': 'Business property',
    'Mobilier Pro': 'Business equipment',
    'LBO/OBO': 'LBO / OBO',
    'Restructuration de dette': 'Debt restructuring',
  },
} as const satisfies Record<Lang, Record<string, string>>;

const murFr = {
  eyebrow: 'Avis clients · Vérifiés',
  titre_vide: 'La confiance se mesure dossier après dossier.',
  titre_plein: ['Des centaines de dossiers.', 'Une note qui parle.'],
  sous: 'Chaque témoignage est déposé sur invitation par un client identifié via son compte Google, après le déblocage de son financement.',
  avenir_titre: 'Les premiers avis vérifiés arrivent bientôt.',
  avenir_texte: 'Le dépôt d’avis est ouvert à nos clients, sur invitation, après le déblocage de leur financement. Aucun avis anonyme, aucun avis acheté.',
  etapes: [
    { titre: 'Invitation', texte: 'Un lien personnel est envoyé au client après le déblocage des fonds.' },
    { titre: 'Connexion Google', texte: 'Le client s’identifie avec son compte : seuls son prénom, son initiale et sa photo apparaissent.' },
    { titre: 'Publication', texte: 'Note, type de projet, montant et ville rejoignent le mur après validation.' },
  ],
  invitation: 'Dépôt sur invitation',
  parler: 'Parlons de votre projet',
  avis_verifies: 'avis vérifiés',
  authentifies: 'Authentifiés par connexion Google',
  carte_legende: 'Nos financements en France',
  carte_note: 'Localisation à la ville, jamais l’adresse exacte.',
  verifie: 'Vérifié',
  astuce: 'Le mur défile — survolez pour le figer',
  voir_plus: 'Voir plus d’avis',
};
const murEn: typeof murFr = {
  eyebrow: 'Client reviews · Verified',
  titre_vide: 'Trust is measured one file at a time.',
  titre_plein: ['Hundreds of files.', 'A rating that speaks.'],
  sous: 'Each testimonial is submitted by invitation by a client identified through their Google account, after their funds are released.',
  avenir_titre: 'The first verified reviews are coming soon.',
  avenir_texte: 'Review submission is open to our clients, by invitation, once their financing is released. No anonymous reviews, no paid reviews.',
  etapes: [
    { titre: 'Invitation', texte: 'A personal link is sent to the client once the funds are released.' },
    { titre: 'Google sign-in', texte: 'The client signs in with their account: only their first name, initial and photo appear.' },
    { titre: 'Publication', texte: 'Rating, project type, amount and city join the wall after validation.' },
  ],
  invitation: 'Submission by invitation',
  parler: 'Let’s discuss your project',
  avis_verifies: 'verified reviews',
  authentifies: 'Authenticated via Google sign-in',
  carte_legende: 'Our financings across France',
  carte_note: 'City-level location, never the exact address.',
  verifie: 'Verified',
  astuce: 'The wall scrolls — hover to pause',
  voir_plus: 'Show more reviews',
};
export const murTextes = (lang: Lang) => (lang === 'en' ? murEn : murFr);

const depotFr = {
  meta_titre: 'Déposer un avis | PEAK FUNDING',
  meta_desc: 'Déposez votre avis vérifié sur votre accompagnement PEAK FUNDING.',
  fil_accueil: 'Accueil',
  fil_page: 'Déposer un avis',
  eyebrow: 'Avis client · Sur invitation',
  titre: 'Votre avis compte.',
  intro: 'Deux minutes : votre note, votre projet et quelques mots. Seuls votre prénom, l’initiale de votre nom et votre photo Google seront publiés.',
  verif_jeton: 'Vérification de votre invitation…',
  jeton_absent: 'Cette page est réservée aux clients invités. Le lien reçu par e-mail contient votre invitation personnelle.',
  jeton_invalide: 'Cette invitation n’est plus valide : elle a déjà servi ou a expiré. Contactez le cabinet pour en recevoir une nouvelle.',
  etape_auth: 'Étape 1 — Identité',
  auth_titre: 'Vérifions qui vous êtes',
  auth_texte: 'Nous ne publions que des avis rattachés à un compte réel. Votre nom complet et votre e-mail restent privés.',
  auth_bouton: 'Continuer avec Google',
  auth_erreur: 'La connexion Google a échoué. Réessayez, ou contactez le cabinet.',
  etape_form: 'Étape 2 — Votre avis',
  form_titre: 'Partagez votre expérience',
  connecte: 'connecté',
  changer: 'changer de compte',
  l_note: 'Votre note',
  note_vide: 'Sélectionnez une note',
  notes: ['', 'Décevant', 'Moyen', 'Correct', 'Très bien', 'Excellent'],
  l_prenom: 'Prénom affiché',
  l_projet: 'Type de projet',
  l_montant: 'Montant du prêt',
  ph_montant: 'ex. 320 000',
  l_ville: 'Ville du projet',
  ph_ville: 'ex. Lyon',
  note_ville: '(jamais l’adresse exacte)',
  l_texte: 'Votre avis',
  ph_texte: 'Comment s’est passé votre accompagnement ?',
  compteur: 'caractères (40 minimum)',
  consent: 'J’autorise PEAK FUNDING à publier cet avis avec mon prénom, l’initiale de mon nom et ma photo Google. Mes coordonnées restent confidentielles.',
  err_champs: 'Merci d’attribuer une note, de renseigner le montant, la ville, un avis d’au moins 40 caractères et de cocher la case.',
  err_envoi: 'L’envoi a échoué. Votre invitation a peut-être déjà été utilisée — contactez le cabinet.',
  envoyer: 'Publier mon avis',
  envoi: 'Envoi…',
  succes_titre: 'Merci pour votre avis !',
  succes_texte: 'Il sera publié sur le site après une courte validation par le cabinet.',
  retour: 'Retour à l’accueil',
};
const depotEn: typeof depotFr = {
  meta_titre: 'Leave a review | PEAK FUNDING',
  meta_desc: 'Leave your verified review of your PEAK FUNDING experience.',
  fil_accueil: 'Home',
  fil_page: 'Leave a review',
  eyebrow: 'Client review · By invitation',
  titre: 'Your review matters.',
  intro: 'Two minutes: your rating, your project and a few words. Only your first name, last-name initial and Google photo will be published.',
  verif_jeton: 'Checking your invitation…',
  jeton_absent: 'This page is reserved for invited clients. The link you received by e-mail contains your personal invitation.',
  jeton_invalide: 'This invitation is no longer valid: it has already been used or has expired. Contact the firm to receive a new one.',
  etape_auth: 'Step 1 — Identity',
  auth_titre: 'Let’s verify who you are',
  auth_texte: 'We only publish reviews tied to a real account. Your full name and e-mail stay private.',
  auth_bouton: 'Continue with Google',
  auth_erreur: 'Google sign-in failed. Try again, or contact the firm.',
  etape_form: 'Step 2 — Your review',
  form_titre: 'Share your experience',
  connecte: 'signed in',
  changer: 'switch account',
  l_note: 'Your rating',
  note_vide: 'Select a rating',
  notes: ['', 'Poor', 'Fair', 'Good', 'Very good', 'Excellent'],
  l_prenom: 'Displayed first name',
  l_projet: 'Project type',
  l_montant: 'Loan amount',
  ph_montant: 'e.g. 320000',
  l_ville: 'Project city',
  ph_ville: 'e.g. Lyon',
  note_ville: '(never the exact address)',
  l_texte: 'Your review',
  ph_texte: 'How did your experience go?',
  compteur: 'characters (40 minimum)',
  consent: 'I authorise PEAK FUNDING to publish this review with my first name, last-name initial and Google photo. My contact details remain confidential.',
  err_champs: 'Please give a rating, enter the amount, the city, a review of at least 40 characters, and tick the box.',
  err_envoi: 'Submission failed. Your invitation may already have been used — contact the firm.',
  envoyer: 'Publish my review',
  envoi: 'Sending…',
  succes_titre: 'Thank you for your review!',
  succes_texte: 'It will be published on the site after a short validation by the firm.',
  retour: 'Back to home',
};
export const depotTextes = (lang: Lang) => (lang === 'en' ? depotEn : depotFr);
