/* Textes des îlots React (parcours de rendez-vous, simulateur), par langue.
   Règle importante : la VALEUR soumise au formulaire (payload Formspree / mail)
   reste en français pour que la boîte de réception du cabinet soit homogène,
   quelle que soit la langue du visiteur. Seuls les LIBELLÉS affichés changent.
   Chaque option est donc { v: valeur canonique FR, l: libellé affiché }. */

import type { Lang } from '../../i18n';

export type Option = { v: string; l: string };

export const rdv = {
  fr: {
    etape1: 'Étape 1 sur 2 — Vous',
    etape2: 'Étape 2 sur 2 — Votre projet',
    merci: 'Merci, c’est noté.',
    aparte1: '2 minutes — pour préparer au mieux notre échange.',
    aparte2: 'Vos attentes de financement',
    prenom: 'Prénom',
    nom: 'Nom',
    email: 'E-mail',
    tel: 'Téléphone',
    ph_email: 'vous@exemple.fr',
    ph_tel: '06 00 00 00 00',
    err1: 'Merci de renseigner votre prénom, votre nom, votre email et votre téléphone.',
    continuer: 'Continuer →',
    l_typeProjet: 'Type de projet',
    l_statut: 'Votre situation',
    l_budget: 'Budget / prix du bien',
    ph_budget: 'ex. 320 000 €',
    l_apport: 'Apport disponible',
    ph_apport: 'ex. 40 000 €',
    l_revenus: 'Revenus nets mensuels du foyer',
    ph_mois: '€ / mois',
    l_charges: 'Charges de prêt en cours',
    l_ville: 'Localisation du bien',
    ph_ville: 'Ville',
    l_avancement: 'Avancement du projet',
    l_delai: 'Délai souhaité',
    l_taux: 'Taux souhaité',
    ph_taux: 'ex. 3,5 %',
    l_duree: 'Durée souhaitée',
    ph_duree: 'ex. 25 ans',
    l_montant: 'Montant d’emprunt souhaité',
    ph_montant: 'ex. 300 000 €',
    l_courtier: 'Courtier souhaité',
    l_message: 'Un point à préciser ?',
    optionnel: '(optionnel)',
    ph_message: 'Votre message',
    consentement:
      'Vos informations sont transmises au cabinet pour préparer le rendez-vous. Aucune donnée n’est partagée avec des tiers.',
    err2: 'Merci de compléter tous les champs et de cocher la case de consentement. Seul le message est optionnel.',
    retour1: '← Étape 1',
    envoyer: 'Envoyer et choisir un créneau',
    recap:
      'Votre récapitulatif a été préparé pour le cabinet. Choisissez maintenant le créneau qui vous convient pour votre premier rendez-vous.',
    choisir: 'Choisissez votre courtier :',
    typeProjet: [
      { v: 'Résidence principale', l: 'Résidence principale' },
      { v: 'Investissement locatif', l: 'Investissement locatif' },
      { v: 'Rachat de crédit', l: 'Rachat de crédit' },
      { v: 'Financement professionnel', l: 'Financement professionnel' },
      { v: 'Autre', l: 'Autre' },
    ] as Option[],
    statut: [
      { v: 'Primo-accédant', l: 'Primo-accédant' },
      { v: 'Déjà propriétaire', l: 'Déjà propriétaire' },
      { v: 'Investisseur locatif', l: 'Investisseur locatif' },
      { v: 'Non-résident / expatrié', l: 'Non-résident / expatrié' },
      { v: 'Autre', l: 'Autre' },
    ] as Option[],
    avancement: [
      { v: 'En recherche de bien', l: 'En recherche de bien' },
      { v: 'Offre en cours', l: 'Offre en cours' },
      { v: 'Offre acceptée', l: 'Offre acceptée' },
      { v: 'Compromis signé', l: 'Compromis signé' },
      { v: 'Simple renseignement', l: 'Simple renseignement' },
    ] as Option[],
    delai: [
      { v: 'Dès que possible', l: 'Dès que possible' },
      { v: 'Sous 3 mois', l: 'Sous 3 mois' },
      { v: 'Sous 6 mois', l: 'Sous 6 mois' },
      { v: 'Pas encore défini', l: 'Pas encore défini' },
    ] as Option[],
    courtier: [
      { v: 'Peu importe', l: 'Peu importe' },
      { v: 'Valentin Boura–Defranoux', l: 'Valentin Boura–Defranoux' },
      { v: 'Maxime Pidoux', l: 'Maxime Pidoux' },
    ] as Option[],
  },
  en: {
    etape1: 'Step 1 of 2 — You',
    etape2: 'Step 2 of 2 — Your project',
    merci: 'Thank you, noted.',
    aparte1: '2 minutes — to make the most of our conversation.',
    aparte2: 'Your financing expectations',
    prenom: 'First name',
    nom: 'Last name',
    email: 'Email',
    tel: 'Phone',
    ph_email: 'you@example.com',
    ph_tel: '+33 6 00 00 00 00',
    err1: 'Please provide your first name, last name, email and phone number.',
    continuer: 'Continue →',
    l_typeProjet: 'Project type',
    l_statut: 'Your situation',
    l_budget: 'Budget / property price',
    ph_budget: 'e.g. €320,000',
    l_apport: 'Available down payment',
    ph_apport: 'e.g. €40,000',
    l_revenus: 'Net monthly household income',
    ph_mois: '€ / month',
    l_charges: 'Current loan payments',
    l_ville: 'Property location',
    ph_ville: 'City',
    l_avancement: 'Project stage',
    l_delai: 'Preferred timeframe',
    l_taux: 'Target rate',
    ph_taux: 'e.g. 3.5%',
    l_duree: 'Target term',
    ph_duree: 'e.g. 25 years',
    l_montant: 'Target loan amount',
    ph_montant: 'e.g. €300,000',
    l_courtier: 'Preferred broker',
    l_message: 'Anything to add?',
    optionnel: '(optional)',
    ph_message: 'Your message',
    consentement:
      'Your information is sent to the firm to prepare the meeting. No data is shared with third parties.',
    err2: 'Please complete every field and tick the consent box. Only the message is optional.',
    retour1: '← Step 1',
    envoyer: 'Send and choose a slot',
    recap:
      'Your summary has been prepared for the firm. Now choose the time slot that suits you for your first meeting.',
    choisir: 'Choose your broker:',
    typeProjet: [
      { v: 'Résidence principale', l: 'Primary residence' },
      { v: 'Investissement locatif', l: 'Buy-to-let investment' },
      { v: 'Rachat de crédit', l: 'Loan buyback' },
      { v: 'Financement professionnel', l: 'Business financing' },
      { v: 'Autre', l: 'Other' },
    ] as Option[],
    statut: [
      { v: 'Primo-accédant', l: 'First-time buyer' },
      { v: 'Déjà propriétaire', l: 'Already a homeowner' },
      { v: 'Investisseur locatif', l: 'Buy-to-let investor' },
      { v: 'Non-résident / expatrié', l: 'Non-resident / expatriate' },
      { v: 'Autre', l: 'Other' },
    ] as Option[],
    avancement: [
      { v: 'En recherche de bien', l: 'Searching for a property' },
      { v: 'Offre en cours', l: 'Offer in progress' },
      { v: 'Offre acceptée', l: 'Offer accepted' },
      { v: 'Compromis signé', l: 'Sale agreement signed' },
      { v: 'Simple renseignement', l: 'Just enquiring' },
    ] as Option[],
    delai: [
      { v: 'Dès que possible', l: 'As soon as possible' },
      { v: 'Sous 3 mois', l: 'Within 3 months' },
      { v: 'Sous 6 mois', l: 'Within 6 months' },
      { v: 'Pas encore défini', l: 'Not yet defined' },
    ] as Option[],
    courtier: [
      { v: 'Peu importe', l: 'No preference' },
      { v: 'Valentin Boura–Defranoux', l: 'Valentin Boura–Defranoux' },
      { v: 'Maxime Pidoux', l: 'Maxime Pidoux' },
    ] as Option[],
  },
} as const;

export const simulateur = {
  fr: {
    projet: 'Votre projet',
    rp: 'Résidence principale',
    loc: 'Investissement locatif',
    revenus: 'Revenus nets mensuels du foyer',
    mois: '€ / mois',
    loyers: 'Loyers attendus',
    loyers_note: '(retenus à 70 % — norme HCSF)',
    autres: 'Autres revenus',
    autres_note: '(revenus locatifs hors charges, salaire variable, revenus mobiliers, etc.)',
    retenus: 'retenus à',
    autres_sr: 'Autres revenus mensuels',
    apport: 'Apport disponible',
    charges: 'Charge(s) de prêt actuelle(s)',
    duree: 'Durée',
    ans: 'ans',
    capacite: 'Capacité estimée',
    soit: 'soit ≈',
    par_mois_sur: '/mois sur',
    endettement: 'Endettement :',
    max: 'max',
    reste: 'Reste à vivre :',
    cta: 'En parler avec un conseiller',
    avert:
      'Estimation donnée à titre indicatif, hors assurance et frais de notaire. Le chiffre exact dépend de votre dossier. Un crédit vous engage et doit être remboursé.',
  },
  en: {
    projet: 'Your project',
    rp: 'Primary residence',
    loc: 'Buy-to-let investment',
    revenus: 'Net monthly household income',
    mois: '€ / month',
    loyers: 'Expected rent',
    loyers_note: '(counted at 70% — HCSF rule)',
    autres: 'Other income',
    autres_note: '(net rental income, variable pay, investment income, etc.)',
    retenus: 'counted at',
    autres_sr: 'Other monthly income',
    apport: 'Available down payment',
    charges: 'Current loan payment(s)',
    duree: 'Term',
    ans: 'years',
    capacite: 'Estimated capacity',
    soit: 'i.e. ≈',
    par_mois_sur: '/month over',
    endettement: 'Debt ratio:',
    max: 'max',
    reste: 'Remaining income:',
    cta: 'Discuss with an adviser',
    avert:
      'Indicative estimate, excluding insurance and notary fees. The exact figure depends on your file. A loan commits you and must be repaid.',
  },
} as const;

export const rdvTextes = (lang: Lang) => rdv[lang];
export const simulateurTextes = (lang: Lang) => simulateur[lang];
